//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Buffer_1
// {
//
//   float4x4 mat;                      // Offset:    0 Size:    64
//   float3 vec;                        // Offset:   64 Size:    12
//   float i;                           // Offset:   76 Size:     4
//
// }
//
// cbuffer Buffer_2
// {
//
//   float4 packed_vec;                 // Offset:    0 Size:    16
//   float packed_float_1;              // Offset:   16 Size:     4
//   float packed_float_2;              // Offset:   20 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Buffer_1                          cbuffer      NA          NA            cb0      1 
// Buffer_2                          cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
vs_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[5], immediateIndexed
dcl_constantbuffer CB2[2], immediateIndexed
dcl_output_siv o0.xyzw, position
dcl_temps 2
add r0.x, cb0[0].y, cb0[0].x
add r0.x, r0.x, cb0[0].z
add r0.x, r0.x, cb0[0].w
add r1.x, cb0[1].y, cb0[1].x
add r1.x, r1.x, cb0[1].z
add r0.y, r1.x, cb0[1].w
add r1.x, cb0[2].y, cb0[2].x
add r1.x, r1.x, cb0[2].z
add r0.z, r1.x, cb0[2].w
add r1.x, cb0[3].y, cb0[3].x
add r1.x, r1.x, cb0[3].z
add r0.w, r1.x, cb0[3].w
add r0.xyzw, r0.xyzw, cb0[4].xyzw
add r0.xyzw, r0.xyzw, cb2[0].xyzw
add o0.xy, r0.xyxx, cb2[1].xyxx
mov o0.zw, r0.zzzw
ret 
// Approximately 17 instruction slots used
