//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyz         0     NONE   float   xyz 
// PSIZE                    0   x           1     NONE   float   x   
// BLENDINDICES             0   x           2     NONE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v0.xyz
dcl_input v1.x
dcl_input v2.x
dcl_output_siv o0.xyzw, position
add o0.z, v0.z, v1.x
utof o0.w, v2.x
mov o0.xy, v0.xyxx
ret 
// Approximately 4 instruction slots used
