//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// A                        0   xyzw        0     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                1   x           1   TARGET   float   x   
// SV_Target                2   xyz         2   TARGET   float   xyz 
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyzw
dcl_output o1.x
dcl_output o2.xyz
dcl_temps 1
dp2 o1.x, v0.zwzz, l(1.000000, 0.003922, 0.000000, 0.000000)
mad r0.xyz, v0.xyzx, l(3.555400, 3.555400, 0.000000, 0.000000), l(-1.777700, -1.777700, 1.000000, 0.000000)
dp3 r0.z, r0.xyzx, r0.xyzx
div r0.z, l(2.000000), r0.z
mul o2.xy, r0.xyxx, r0.zzzz
add o2.z, r0.z, l(-1.000000)
ret 
// Approximately 7 instruction slots used
