//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// A                        0   xyzw        0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyz
dcl_output o0.xyz
dcl_temps 1
mad r0.xyz, v0.xyzx, l(3.555400, 3.555400, 0.000000, 0.000000), l(-1.777700, -1.777700, 1.000000, 0.000000)
dp3 r0.z, r0.xyzx, r0.xyzx
div r0.z, l(2.000000), r0.z
mul o0.xy, r0.xyxx, r0.zzzz
add o0.z, r0.z, l(-1.000000)
ret 
// Approximately 6 instruction slots used
