//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// A                        0   xyz         0     NONE   float   xyz 
// B                        0   xyzw        1     NONE   float   xyzw
// C                        0   xyz         2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyz
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_output o0.xyz
dcl_temps 1
add r0.xyz, v1.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
dp3 r0.x, v2.xyzx, r0.xyzx
add r0.x, r0.x, l(0.500000)
mul r0.xyz, r0.xxxx, v0.xyzx
max r0.w, v1.w, l(0.000100)
div o0.xyz, r0.xyzx, r0.wwww
ret 
// Approximately 7 instruction slots used
