//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xy          0   TARGET   float   xy  
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyz
dcl_output o0.xy
dcl_temps 1
add r0.x, v0.z, l(1.000000)
div r0.xy, v0.xyxx, r0.xxxx
mad o0.xy, r0.xyxx, l(0.281262, 0.281262, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
ret 
// Approximately 4 instruction slots used
