//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// A                        0   x           0     NONE   float   x   
// B                        0    yzw        0     NONE   float    yzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.x
dcl_input_ps linear v0.yzw
dcl_output o0.xyzw
dcl_temps 1
add r0.x, v0.w, l(1.000000)
div r0.xy, v0.yzyy, r0.xxxx
mad o0.xy, r0.xyxx, l(0.281262, 0.281262, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
mul r0.xy, v0.xxxx, l(1.000000, 255.000000, 0.000000, 0.000000)
frc r0.xy, r0.xyxx
mad o0.z, -r0.y, l(0.003922), r0.x
mov o0.w, r0.y
ret 
// Approximately 8 instruction slots used
