//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// A                        0   x           0     NONE   float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   x           0   TARGET   float   x   
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.x
dcl_output o0.x
dcl_temps 1
ge r0.x, l(0.040450), v0.x
if_nz r0.x
  mul o0.x, v0.x, l(0.077399)
  ret 
else 
  lt r0.x, v0.x, l(1.000000)
  if_nz r0.x
    add r0.x, v0.x, l(0.055000)
    mul r0.x, r0.x, l(0.947867)
    log r0.x, r0.x
    mul r0.x, r0.x, l(2.400000)
    exp o0.x, r0.x
    ret 
  else 
    log r0.x, v0.x
    mul r0.x, r0.x, l(2.200000)
    exp o0.x, r0.x
    ret 
  endif 
endif 
ret 
// Approximately 21 instruction slots used
