//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyz
dcl_output o0.xyz
dcl_temps 1
mad r0.xyz, v0.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
mad r0.xyz, v0.xyzx, r0.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
mul o0.xyz, r0.xyzx, v0.xyzx
ret 
// Approximately 4 instruction slots used
