//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// A                        0   xyzw        0     NONE   float   xyzw
// B                        0   xyzw        1     NONE   float   xyzw
// C                        0   xyzw        2     NONE   float   xyzw
// D                        0   xyz         3     NONE   float   xyz 
// E                        0   xyz         4     NONE   float   xyz 
// F                        0   xyz         5     NONE   float   xyz 
// G                        0   xyz         6     NONE   float   xyz 
// H                        0   xyzw        7     NONE   float   xyzw
// I                        0   xyz         8     NONE   float   xyz 
// J                        0   xyz         9     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.xyzw
dcl_input_ps linear v8.xyz
dcl_input_ps linear v9.xyz
dcl_output o0.xyz
dcl_temps 3
add r0.xyzw, v1.xyzw, -v8.yyyy
mul r1.xyzw, r0.xyzw, r0.xyzw
mul r0.xyzw, r0.xyzw, v9.yyyy
add r2.xyzw, v0.xyzw, -v8.xxxx
mad r1.xyzw, r2.xyzw, r2.xyzw, r1.xyzw
mad r0.xyzw, r2.xyzw, v9.xxxx, r0.xyzw
add r2.xyzw, v2.xyzw, -v8.zzzz
mad r1.xyzw, r2.xyzw, r2.xyzw, r1.xyzw
mad r0.xyzw, r2.xyzw, v9.zzzz, r0.xyzw
max r1.xyzw, r1.xyzw, l(0.000001, 0.000001, 0.000001, 0.000001)
rsq r2.xyzw, r1.xyzw
mad r1.xyzw, r1.xyzw, v7.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
div r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000), r1.xyzw
mul r0.xyzw, r0.xyzw, r2.xyzw
max r0.xyzw, r0.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r0.xyzw, r1.xyzw, r0.xyzw
mul r1.xyz, r0.yyyy, v4.xyzx
mad r1.xyz, v3.xyzx, r0.xxxx, r1.xyzx
mad r0.xyz, v5.xyzx, r0.zzzz, r1.xyzx
mad o0.xyz, v6.xyzx, r0.wwww, r0.xyzx
ret 
// Approximately 21 instruction slots used
