//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xy w
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyw
dcl_output o0.xyz
dcl_temps 1
mul r0.x, v0.w, v0.x
mov r0.y, v0.y
mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
dp2 r0.z, r0.xyxx, r0.xyxx
mov o0.xy, r0.xyxx
min r0.x, r0.z, l(1.000000)
add r0.x, -r0.x, l(1.000000)
sqrt o0.z, r0.x
ret 
// Approximately 9 instruction slots used
