//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// mainTex                           sampler      NA          NA             s0      1 
// mainTex                           texture  float4          2d             t0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xy          0     NONE   float   xy  
// COLOR                    1   xyzw        1     NONE   float   xyzw
// COLOR                    2   xyzw        2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v0.xy
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_output o0.xyzw
dcl_temps 2
sample r0.xyzw, v0.xyxx, t0.xyzw, s0
mul r1.xyz, r0.wwww, v2.xyzx
mad o0.xyz, r0.xyzx, v1.xyzx, r1.xyzx
mul o0.w, r0.w, v1.w
ret 
// Approximately 5 instruction slots used
